apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: daemonset-test1
  labels:
    k8s-app: daemonset-test1
spec:
  selector:
    matchLabels:
      name: daemonset-test1
  template:
    metadata:
      labels:
        name: daemonset-test1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: daemonset-test1
        image: tjcordingly/container-utils:latest
      terminationGracePeriodSeconds: 30
